# Generated by Django 4.2.6 on 2023-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='assembly_line',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='balance_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='company',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='machine_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='manager',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='planned_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='plant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='product_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='remaining_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='shopfloor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
