# Generated by Django 4.2.1 on 2023-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productionPlanning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField()),
                ('employee_id', models.CharField()),
                ('product_id', models.CharField()),
                ('drawing_no', models.CharField()),
                ('customer', models.CharField()),
                ('po_no', models.CharField()),
                ('batch_no', models.CharField()),
                ('quantity', models.IntegerField()),
                ('assigned_date', models.DateField()),
                ('expected_date', models.DateField()),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_planning',
            },
        ),
    ]
