# Generated by Django 4.2.1 on 2023-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineMachineConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jod_id', models.CharField()),
                ('company', models.CharField()),
                ('plant', models.CharField()),
                ('shopfloor', models.CharField()),
                ('product_id', models.CharField()),
                ('stage', models.CharField()),
                ('operation_stage', models.CharField()),
                ('product_target', models.IntegerField()),
                ('skill_matrix', models.CharField()),
                ('assembly_line', models.CharField()),
                ('machine_id', models.CharField()),
                ('date', models.DateField()),
                ('shift_a', models.CharField()),
                ('shift_b', models.CharField()),
                ('shift_c', models.CharField()),
            ],
            options={
                'db_table': 'line_machine_config',
            },
        ),
    ]
