# Generated by Django 4.2.6 on 2023-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_linemachineconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanning',
            name='required_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='batch_no',
            field=models.CharField(default='BATCH001', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='customer',
            field=models.CharField(default='CUSTOMER A', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='drawing_no',
            field=models.CharField(default='TEST', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='employee_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='job_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='po_no',
            field=models.CharField(default='TEST', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
