# Generated by Django 4.2.6 on 2023-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionplanning_required_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='job_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
