# Generated by Django 4.2.6 on 2023-10-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productionplanning_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='batch_no',
            field=models.CharField(max_length=100),
        ),
    ]
