# Generated by Django 4.2.6 on 2023-10-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_productionplanning_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
