# Generated by Django 4.2.6 on 2023-10-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionplanning_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
