# Generated by Django 4.2.6 on 2023-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_productionplanning_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='required_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
