# Generated by Django 4.2.6 on 2023-10-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_productionplanning_required_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineMachineSlotConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField()),
                ('date', models.DateField()),
                ('shift_a', models.CharField()),
                ('shift_b', models.CharField()),
                ('shift_c', models.CharField()),
                ('planned_hours', models.IntegerField()),
                ('planned_production', models.IntegerField()),
                ('remaining_hours', models.IntegerField()),
                ('balance_production', models.IntegerField()),
                ('manager', models.CharField(default='XYZ')),
            ],
            options={
                'db_table': 'line_machine_slot_config',
            },
        ),
        migrations.AlterField(
            model_name='linemachineconfig',
            name='shift_a',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linemachineconfig',
            name='shift_b',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linemachineconfig',
            name='shift_c',
            field=models.CharField(blank=True, null=True),
        ),
    ]
