# Generated by Django 4.2.6 on 2023-10-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_linemachineslotconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemachineslotconfig',
            name='shift_a',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linemachineslotconfig',
            name='shift_b',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linemachineslotconfig',
            name='shift_c',
            field=models.CharField(blank=True, null=True),
        ),
    ]
