# Generated by Django 4.2.6 on 2023-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_linemachineslotconfig_shift_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemachineslotconfig',
            name='planned_production',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
