# Generated by Django 4.2.6 on 2023-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_linemachineslotconfig_planned_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='job_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
