# Generated by Django 4.2.6 on 2023-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_linemachineslotconfig_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='assembly_line',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='company',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='machine_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='plant',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linemachineslotconfig',
            name='shopfloor',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='job_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
