# Generated by Django 4.2.6 on 2023-10-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_linemachineslotconfig_assembly_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linemachineconfig',
            old_name='shift_a',
            new_name='assigned_end_production',
        ),
        migrations.RenameField(
            model_name='linemachineconfig',
            old_name='shift_b',
            new_name='assigned_start_production',
        ),
        migrations.RenameField(
            model_name='linemachineconfig',
            old_name='shift_c',
            new_name='break_time',
        ),
        migrations.RenameField(
            model_name='linemachineconfig',
            old_name='operation_stage',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='linemachineconfig',
            name='date',
        ),
        migrations.RemoveField(
            model_name='linemachineconfig',
            name='skill_matrix',
        ),
        migrations.RemoveField(
            model_name='linemachineconfig',
            name='stage',
        ),
        migrations.AddField(
            model_name='linemachineconfig',
            name='required_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linemachineconfig',
            name='total_order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linemachineconfig',
            name='product_target',
            field=models.IntegerField(default='00:01:00'),
        ),
    ]
