# Generated by Django 4.2.6 on 2023-10-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_linemachineconfig_total_order'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='linemachineconfig',
    #         name='product_target',
    #         field=models.TimeField(default='00:01:00'),
    #     ),
    # ]
