# Generated by Django 4.2.6 on 2023-10-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_linemachineconfig_product_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemachineconfig',
            name='product_target',
            field=models.CharField(default='00:01:00'),
        ),
    ]
