# Generated by Django 4.2.6 on 2023-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_alter_linemachineconfig_product_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemachineconfig',
            name='break_time',
            field=models.CharField(blank=True, default='01:00:00', null=True),
        ),
    ]
