# Generated by Django 4.2.6 on 2023-10-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_alter_linemachineconfig_break_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linemachineconfig',
            old_name='jod_id',
            new_name='job_id',
        ),
    ]
