# Generated by Django 4.2.6 on 2023-10-30 05:54

from django.db import migrations, models
import production.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_rename_jod_id_linemachineconfig_job_id'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='machineWiseData',
    #         fields=[
    #             ('id', models.AutoField(primary_key=True, serialize=False)),
    #             ('plant', models.CharField(default='PUNE')),
    #             ('shopfloor', models.CharField(default='XYZ')),
    #             ('assembly_line', models.CharField(default='TSE')),
    #             ('time', models.CharField(default=production.models.machineWiseData.generate_time_range)),
    #         ],
    #     ),
    # ]
