# Generated by Django 4.2.6 on 2023-10-30 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_machinewisedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='machineWiseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(default='PUNE')),
                ('shopfloor', models.CharField(default='XYZ')),
                ('assembly_line', models.CharField(default='TSE')),
                ('time', models.CharField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'machine_wise_data',
                'unique_together': {('date', 'time')},
            },
        ),
    ]
