# Generated by Django 4.2.6 on 2023-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_machinewisedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='date',
            field=models.DateField(),
        ),
    ]
