# Generated by Django 4.2.6 on 2023-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_alter_machinewisedata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinewisedata',
            name='actual',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinewisedata',
            name='idle_time',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinewisedata',
            name='on_time',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinewisedata',
            name='performance',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinewisedata',
            name='target',
            field=models.IntegerField(default=60),
        ),
    ]
