# Generated by Django 4.2.6 on 2023-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_machinewisedata_actual_machinewisedata_idle_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='idle_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='performance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='target',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
