# Generated by Django 4.2.6 on 2023-10-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_alter_machinewisedata_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
