# Generated by Django 4.2.6 on 2023-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_machinewisedata_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinewisedata',
            name='machine_id',
            field=models.CharField(default='TSE-001'),
        ),
        migrations.AddField(
            model_name='machinewisedata',
            name='product_target',
            field=models.IntegerField(default=60),
        ),
    ]
