# Generated by Django 4.2.6 on 2023-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_productionplanning_product_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanning',
            name='drawing_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionplanning',
            name='po_no',
            field=models.CharField(max_length=100),
        ),
    ]
