# Generated by Django 4.2.6 on 2023-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_alter_machinewisedata_machine_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinewisedata',
            unique_together={('machine_id', 'date', 'time')},
        ),
    ]
