# Generated by Django 4.2.6 on 2023-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_alter_linemachineconfig_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='target',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
    ]
