# Generated by Django 4.2.6 on 2023-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_alter_machinewisedata_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinewisedata',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
