# Generated by Django 4.2.6 on 2023-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_machinewisedata_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='assembly_line',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='plant',
            field=models.CharField(default='Ferozepur', max_length=255),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='shopfloor',
            field=models.CharField(default='Module Line - 1', max_length=255),
        ),
    ]
