# Generated by Django 4.2.6 on 2024-01-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0037_alter_machinewisedata_assembly_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assemblyLineWiseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=255)),
                ('shopfloor', models.CharField(max_length=255)),
                ('assemblyline', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('date_production', models.CharField(max_length=255)),
                ('stages', models.IntegerField()),
            ],
        ),
    ]
