# Generated by Django 4.2.6 on 2024-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_assemblylinewisedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblylinewisedata',
            name='shift_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
