# Generated by Django 4.2.6 on 2024-01-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0040_alter_assemblylinewisedata_shift_name'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='assemblylinewisedata',
        #     name='shift_name',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='assemblylinewisedata',
        #     name='stages',
        #     field=models.JSONField(),
        # ),
    ]
