# Generated by Django 4.2.6 on 2024-01-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_alter_assemblylinewisedata_shift_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assemblyLineWiseData',
        ),
    ]
