# Generated by Django 4.2.6 on 2024-01-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_assemblylinewisedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblylinewisedata',
            name='stages',
        ),
        migrations.CreateModel(
            name='soloAssemblyLineData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_no', models.IntegerField()),
                ('stage_name', models.CharField(max_length=255)),
                ('mc_on_hours', models.IntegerField()),
                ('mc_idle_hours', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('target', models.IntegerField()),
                ('performance', models.FloatField()),
                ('current', models.FloatField()),
                ('assembly_line_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.assemblylinewisedata')),
            ],
            options={
                'db_table': 'solo_assembly_line_data',
            },
        ),
    ]
