# Generated by Django 4.2.6 on 2024-01-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_remove_assemblylinewisedata_stages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soloassemblylinedata',
            old_name='stage_name',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='soloassemblylinedata',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='mc_idle_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='mc_on_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
