# Generated by Django 4.2.6 on 2024-01-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_remove_soloassemblylinedata_assembly_line_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloassemblylinedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soloassemblylinedata',
            name='shift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
