# Generated by Django 4.2.6 on 2024-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0047_soloassemblylinedata_date_soloassemblylinedata_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAndon',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_datetime', models.DateTimeField(blank=True, null=True)),
                ('machine_status', models.CharField(blank=True, max_length=255, null=True)),
                ('production_count', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_reading', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_andon',
            },
        ),
    ]
