# Generated by Django 4.2.6 on 2024-01-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0048_productionandon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionandon',
            options={'managed': True},
        ),
    ]
