# Generated by Django 4.2.6 on 2024-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0049_alter_productionandon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionandon',
            options={'managed': False},
        ),
    ]
