# Generated by Django 4.2.6 on 2024-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0050_alter_productionandon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemachineconfig',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linemachineconfig',
            name='product_target',
            field=models.CharField(max_length=255),
        ),
    ]
