# Generated by Django 4.2.6 on 2024-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_linemachineconfig_stage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='spellAssemblyLineData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_no', models.IntegerField()),
                ('stage', models.CharField(max_length=255)),
                ('mc_on_hours', models.IntegerField(blank=True, null=True)),
                ('mc_idle_hours', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('performance', models.FloatField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spell_assembly_line_data',
            },
        ),
    ]
