# Generated by Django 4.2.6 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_excelimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelimport',
            old_name='field1',
            new_name='spells',
        ),
        migrations.RemoveField(
            model_name='excelimport',
            name='field2',
        ),
        migrations.AddField(
            model_name='excelimport',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelimport',
            name='production',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelimport',
            name='shift',
            field=models.CharField(default=None, max_length=55),
            preserve_default=False,
        ),
    ]
