# Generated by Django 4.2.6 on 2024-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0054_rename_field1_excelimport_spells_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='target',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
