# Generated by Django 4.2.6 on 2024-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_excelimport_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellassemblylinedata',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
