# Generated by Django 4.2.6 on 2024-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0057_spellassemblylinedata_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w1_target', models.IntegerField(blank=True, null=True)),
                ('w1_actual', models.IntegerField(blank=True, null=True)),
                ('w2_target', models.IntegerField(blank=True, null=True)),
                ('w2_actual', models.IntegerField(blank=True, null=True)),
                ('w3_target', models.IntegerField(blank=True, null=True)),
                ('w3_actual', models.IntegerField(blank=True, null=True)),
                ('w4_target', models.IntegerField(blank=True, null=True)),
                ('w4_actual', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_target',
            },
        ),
    ]
