# Generated by Django 4.2.6 on 2024-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0058_weeklytarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w1_shift', models.IntegerField(blank=True, null=True)),
                ('w2_shift', models.IntegerField(blank=True, null=True)),
                ('w3_shift', models.IntegerField(blank=True, null=True)),
                ('w4_shift', models.IntegerField(blank=True, null=True)),
                ('shift_total', models.IntegerField(blank=True, null=True)),
                ('w1_target', models.IntegerField(blank=True, null=True)),
                ('w2_target', models.IntegerField(blank=True, null=True)),
                ('w3_target', models.IntegerField(blank=True, null=True)),
                ('w4_target', models.IntegerField(blank=True, null=True)),
                ('target_total', models.IntegerField(blank=True, null=True)),
                ('w1_production', models.IntegerField(blank=True, null=True)),
                ('w2_production', models.IntegerField(blank=True, null=True)),
                ('w3_production', models.IntegerField(blank=True, null=True)),
                ('w4_production', models.IntegerField(blank=True, null=True)),
                ('production_total', models.IntegerField(blank=True, null=True)),
                ('today_rate', models.IntegerField(blank=True, null=True)),
                ('days_completed', models.IntegerField(blank=True, null=True)),
                ('holidays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_target',
            },
        ),
    ]
