# Generated by Django 4.2.6 on 2023-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assemblyline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assemblyline_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assemblyline',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='shopfloor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shopfloor_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shopfloor',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='drawing_no',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
