# Generated by Django 4.2.6 on 2023-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_assemblyline_company_plant_shopfloor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
