# Generated by Django 4.2.6 on 2023-11-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='poNo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'po_no',
            },
        ),
    ]
