# Generated by Django 4.2.6 on 2023-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_batch_pono'),
    ]

    operations = [
        migrations.CreateModel(
            name='productReceipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=100)),
                ('stages', models.IntegerField(max_length=100)),
                ('target_per_unit', models.TimeField(max_length=100)),
                ('target_per_minute', models.TimeField(max_length=100)),
                ('target_per_hour', models.TimeField(max_length=100)),
                ('skill_matrix', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_receipe',
            },
        ),
    ]
