# Generated by Django 4.2.6 on 2023-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_productreceipe_skill_matrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreceipe',
            name='target_per_hour',
        ),
        migrations.RemoveField(
            model_name='productreceipe',
            name='target_per_minute',
        ),
        migrations.AddField(
            model_name='productreceipe',
            name='units_per_hour',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreceipe',
            name='units_per_minute',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
