# Generated by Django 4.2.6 on 2023-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_remove_productreceipe_target_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='target_per_unit',
            field=models.DurationField(),
        ),
    ]
