# Generated by Django 4.2.6 on 2023-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_productreceipe_target_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='units_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreceipe',
            name='units_per_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
