# Generated by Django 4.2.6 on 2023-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_productreceipe_units_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='units_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreceipe',
            name='units_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
