# Generated by Django 4.2.6 on 2023-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_attendancerules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='skill_matrix',
            field=models.CharField(max_length=255),
        ),
    ]
