# Generated by Django 4.2.6 on 2023-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_products_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stages',
            field=models.IntegerField(null=True),
        ),
    ]
