# Generated by Django 4.2.6 on 2023-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_alter_products_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('stages', models.IntegerField()),
                ('target_per_unit', models.DurationField()),
                ('units_per_minute', models.FloatField(blank=True, null=True)),
                ('units_per_hour', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'product_recipe2',
            },
        ),
    ]
