# Generated by Django 4.2.6 on 2023-12-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_productrecipe2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRecipe2',
        ),
    ]
