# Generated by Django 4.2.6 on 2023-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_delete_productrecipe2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('stages', models.JSONField()),
            ],
            options={
                'db_table': 'product_recipe2',
            },
        ),
    ]
