# Generated by Django 4.2.6 on 2024-01-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_productrecipe2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productReceipe',
        ),
    ]
