# Generated by Django 4.2.6 on 2024-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_delete_productreceipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCDefectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('defect_name', models.CharField(max_length=255)),
                ('defect_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'qc_defect_type',
            },
        ),
    ]
