# Generated by Django 4.2.6 on 2024-01-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_qcdefecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcdefecttype',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.products'),
            preserve_default=False,
        ),
    ]
