# Generated by Django 4.2.6 on 2024-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_qcdefecttype_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionParameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'inspection_parameters',
            },
        ),
    ]
