# Generated by Django 4.2.6 on 2024-01-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_qcdefecttype_parameter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('lunch_break', models.DurationField()),
                ('tea_break', models.DurationField()),
                ('total_working_hours', models.DurationField()),
            ],
            options={
                'db_table': 'shift_timing',
            },
        ),
    ]
