# Generated by Django 4.2.6 on 2024-01-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_shifttiming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifttiming',
            old_name='tea_break',
            new_name='cleaning_downtime',
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='spell_downtime',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_1',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_2',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_3',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
