# Generated by Django 4.2.6 on 2024-01-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_rename_tea_break_shifttiming_cleaning_downtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifttiming',
            old_name='lunch_break',
            new_name='lunch_break_end',
        ),
        migrations.RenameField(
            model_name='shifttiming',
            old_name='tea_break_1',
            new_name='lunch_break_start',
        ),
        migrations.RenameField(
            model_name='shifttiming',
            old_name='tea_break_2',
            new_name='tea_break_1_end',
        ),
        migrations.RenameField(
            model_name='shifttiming',
            old_name='tea_break_3',
            new_name='tea_break_1_start',
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_2_end',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_2_start',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_3_end',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tea_break_3_start',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
