# Generated by Django 4.2.6 on 2024-01-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_rename_lunch_break_shifttiming_lunch_break_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttiming',
            name='lunch_break_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='lunch_break_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_1_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_1_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_2_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_2_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_3_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_3_start',
            field=models.TimeField(),
        ),
    ]
