# Generated by Django 4.2.6 on 2024-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_alter_shifttiming_lunch_break_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttiming',
            name='cleaning_downtime',
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='cleaning_end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='cleaning_start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
