# Generated by Django 4.2.6 on 2023-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andon',
            fields=[
                ('assemblyline', models.CharField(max_length=30)),
                ('machineId', models.CharField(max_length=50)),
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('andon_alerts', models.DateTimeField(blank=True, null=True)),
                ('andon_acknowledge', models.DateTimeField(blank=True, null=True)),
                ('andon_resolved', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'andon',
            },
        ),
        migrations.CreateModel(
            name='AndonData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='SKF', max_length=10)),
                ('location', models.CharField(default='BLR', max_length=10)),
                ('shopfloor', models.CharField(default='GRINDING', max_length=30)),
                ('assemblyline', models.CharField(max_length=30)),
                ('machineId', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_shift', models.CharField(max_length=10)),
                ('andon_alerts', models.CharField(blank=True, max_length=100, null=True)),
                ('andon_acknowledge', models.CharField(blank=True, max_length=100, null=True)),
                ('andon_resolved', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.CharField(blank=True, max_length=100, null=True)),
                ('repair_time', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'andon_data',
            },
        ),
        migrations.CreateModel(
            name='Assemblyline',
            fields=[
                ('assemblylineId', models.AutoField(primary_key=True, serialize=False)),
                ('assemblylineName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownCategory',
            fields=[
                ('breakdownCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('breakdownCategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownHMI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=55)),
                ('channel_id', models.CharField(max_length=55)),
                ('timestamp', models.DateTimeField()),
                ('breakdown_alert', models.CharField(max_length=255)),
                ('alert_value', models.IntegerField()),
            ],
            options={
                'db_table': 'breakdown_hmi',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machineId', models.AutoField(primary_key=True, serialize=False)),
                ('machineName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftId', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField(blank=True, null=True)),
                ('lunch_end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopfloor',
            fields=[
                ('shopfloorId', models.AutoField(primary_key=True, serialize=False)),
                ('shopfloorName', models.CharField(max_length=100)),
            ],
        ),
    ]
