# Generated by Django 4.2.6 on 2024-01-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
